#서버가 실행되면 자동으로 로딩되는 파일
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 740568103359-rba2il7jtk3qdu79r7iohocl34f5iu5s.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot